/**
 * Hooks generator.
 *
 * Produces .claude/hooks/ shell scripts based on detected formatters,
 * linters, and type checkers. Hooks are triggered at specific points
 * in the Claude Code session lifecycle.
 */

import type { GeneratorContext, Generator } from './types.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface HookFile {
  /** Filename under .claude/hooks/, e.g. "pre-commit.sh". */
  filename: string;
  /** Shell script content. */
  content: string;
}

// ---------------------------------------------------------------------------
// Hook builders
// ---------------------------------------------------------------------------

function buildPreCommitHook(ctx: GeneratorContext): HookFile | null {
  const { formatters, linters } = ctx.repoProfile.tooling;
  const hasTypeScript = ctx.repoProfile.languages.some(
    (l) => l.name.toLowerCase() === 'typescript',
  );

  // Only generate if there's something to run
  if (formatters.length === 0 && linters.length === 0 && !hasTypeScript) {
    return null;
  }

  const lines: string[] = [
    '#!/bin/bash',
    '# Generated by claude-adapt init',
    `# Detected: ${[...formatters, ...linters, hasTypeScript ? 'TypeScript' : ''].filter(Boolean).join(' + ')}`,
    '',
    'set -e',
    '',
    'STAGED=$(git diff --cached --name-only -z --diff-filter=ACMR)',
    '',
    'if [ -z "$STAGED" ]; then',
    '  echo "No staged files."',
    '  exit 0',
    'fi',
    '',
  ];

  // Formatter step
  if (formatters.includes('prettier')) {
    lines.push(
      '# Format staged files',
      'echo "Formatting..."',
      'echo -n "$STAGED" | grep -zE \'\\.(ts|tsx|js|jsx|json|css|scss|md)$\' | xargs -0 npx prettier --write 2>/dev/null || true',
      '',
    );
  }
  if (formatters.includes('black')) {
    lines.push(
      '# Format Python files',
      'echo "Formatting Python..."',
      'echo -n "$STAGED" | grep -zE \'\\.py$\' | xargs -0 black 2>/dev/null || true',
      '',
    );
  }

  // Linter step
  if (linters.includes('eslint')) {
    lines.push(
      '# Lint staged files',
      'echo "Linting..."',
      'echo -n "$STAGED" | grep -zE \'\\.(ts|tsx|js|jsx)$\' | xargs -0 npx eslint --fix 2>/dev/null || true',
      '',
    );
  }
  if (linters.includes('ruff')) {
    lines.push(
      '# Lint Python files',
      'echo "Linting Python..."',
      'echo -n "$STAGED" | grep -zE \'\\.py$\' | xargs -0 ruff check --fix 2>/dev/null || true',
      '',
    );
  }

  // Type check step
  if (hasTypeScript) {
    lines.push(
      '# Type check',
      'echo "Type checking..."',
      'npx tsc --noEmit 2>/dev/null || {',
      '  echo "Type errors found. Review before committing."',
      '  exit 1',
      '}',
      '',
    );
  }

  // Re-stage formatted files
  lines.push(
    '# Re-stage formatted/fixed files',
    'echo -n "$STAGED" | xargs -0 git add 2>/dev/null || true',
    '',
    'echo "Pre-commit checks passed."',
  );

  return {
    filename: 'pre-commit.sh',
    content: lines.join('\n') + '\n',
  };
}

function buildPostSessionHook(_ctx: GeneratorContext): HookFile {
  return {
    filename: 'post-session.sh',
    content: `#!/bin/bash
# Generated by claude-adapt init
# Triggers Phase 4 sync after a Claude Code session ends.
# This hook collects session insights and updates configuration.

set -e

# Check if claude-adapt is available
if ! command -v claude-adapt &> /dev/null; then
  # Try via npx
  npx claude-adapt sync --auto 2>/dev/null || true
else
  claude-adapt sync --auto 2>/dev/null || true
fi
`,
  };
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

export const hooksGenerator: Generator<Record<string, string>> = {
  name: 'hooks',

  async generate(ctx: GeneratorContext): Promise<Record<string, string>> {
    const hooks: Record<string, string> = {};

    const preCommit = buildPreCommitHook(ctx);
    if (preCommit) {
      hooks[preCommit.filename] = preCommit.content;
    }

    const postSession = buildPostSessionHook(ctx);
    hooks[postSession.filename] = postSession.content;

    return hooks;
  },
};
